language: node_js
node_js:
  - 0.8

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g karma
  - npm install --quiet -g grunt-cli
  - npm install --quiet
  - cd cabble
  - node server.js &
  - sleep 3 # give server some time to start
  - cd ../glark

script:
  - grunt jshint
  - karma start ./config/karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox
  - karma start ./config/karma-e2e.conf.js --reporters=dots --browsers=Firefox

notifications:
  email:
    - staff@glark.io
